// package com.majlishekhidmat.controller;

// import com.majlishekhidmat.dto.LoginDto;
// import com.majlishekhidmat.entity.Admin;
// import com.majlishekhidmat.entity.User;
// import com.majlishekhidmat.repository.AdminRepository;
// import com.majlishekhidmat.repository.UserRepository;
// import com.majlishekhidmat.service.AuthService;
// import lombok.RequiredArgsConstructor;
// import org.springframework.http.ResponseEntity;
// import org.springframework.web.bind.annotation.*;

// import java.util.HashMap;
// import java.util.Map;

// @RestController
// @RequestMapping("/api/auth")
// @RequiredArgsConstructor
// @CrossOrigin(origins = {"http://localhost:3000", "http://localhost:5173"})
// public class AuthController {

//     private final AuthService authService;
//     private final UserRepository userRepository;
//     private final AdminRepository adminRepository;

//     @GetMapping("/get-role")
//     public ResponseEntity<?> getRole(@RequestParam String email) {
//         return userRepository.findByEmailIgnoreCase(email)
//                 .map(user -> ResponseEntity.ok(Map.of("role", normalizeRole(user.getRole(), "ROLE_USER"))))
//                 .or(() -> adminRepository.findByEmailIgnoreCase(email)
//                         .map(admin -> ResponseEntity.ok(Map.of("role", normalizeRole(admin.getRole(), "ROLE_ADMIN")))))
//                 .orElseGet(() -> ResponseEntity.status(404).body(Map.of("error", "User not found")));
//     }

//     @PostMapping("/login")
//     public ResponseEntity<?> login(@RequestBody LoginDto loginDto) {
//         return handleLogin(loginDto, false);
//     }

//     @PostMapping("/admin/login")
//     public ResponseEntity<?> adminLogin(@RequestBody LoginDto loginDto) {
//         return handleLogin(loginDto, true);
//     }

//     private ResponseEntity<?> handleLogin(LoginDto loginDto, boolean isAdmin) {
//         try {
//             // JWT token generated by AuthService.login()
//             String token = authService.login(loginDto);

//             String email = loginDto.getEmail();
//             String role = isAdmin ? "ROLE_ADMIN" : "ROLE_USER";

//             Map<String, Object> response = new HashMap<>();
//             response.put("accessToken", token);
//             response.put("role", role);

//             if (isAdmin) {
//                 Admin admin = adminRepository.findByEmailIgnoreCase(email)
//                         .orElseThrow(() -> new RuntimeException("Admin not found"));
//                 addProfileInfo(response, admin);
//             } else {
//                 User user = userRepository.findByEmailIgnoreCase(email)
//                         .orElseThrow(() -> new RuntimeException("User not found"));
//                 addProfileInfo(response, user);
//             }

//             return ResponseEntity.ok(response);
//         } catch (RuntimeException ex) {
//             return ResponseEntity.badRequest().body(Map.of("error", ex.getMessage()));
//         }
//     }

//     private void addProfileInfo(Map<String, Object> response, Object entity) {
//         if (entity instanceof User user) {
//             response.put("email", user.getEmail());
//             response.put("name", user.getName());
//             response.put("phone", user.getPhone());
//             response.put("address", user.getAddress());
//             response.put("dob", user.getDob());
//             response.put("gender", user.getGender());
//             response.put("profilePic", user.getProfilePic());
//         } else if (entity instanceof Admin admin) {
//             response.put("email", admin.getEmail());
//             response.put("name", admin.getName());
//             response.put("phone", admin.getPhone());
//             response.put("address", admin.getAddress());
//             response.put("dob", admin.getDob());
//             response.put("gender", admin.getGender());
//             response.put("profilePic", admin.getProfilePic());
//         }
//     }

//     private String normalizeRole(String role, String defaultRole) {
//         if (role == null || role.isEmpty()) return defaultRole;
//         if (!role.startsWith("ROLE_")) return "ROLE_" + role.toUpperCase();
//         return role;
//     }
// }








package com.majlishekhidmat.controller;

import com.majlishekhidmat.dto.LoginDto;
import com.majlishekhidmat.entity.Admin;
import com.majlishekhidmat.entity.User;
import com.majlishekhidmat.repository.AdminRepository;
import com.majlishekhidmat.repository.UserRepository;
import com.majlishekhidmat.service.AuthService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.HashMap;
import java.util.Map;

@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor
@CrossOrigin(origins = {"http://localhost:3000", "http://localhost:5173"})
public class AuthController {

    private final AuthService authService;
    private final UserRepository userRepository;
    private final AdminRepository adminRepository;

    @GetMapping("/get-role")
    public ResponseEntity<?> getRole(@RequestParam String email) {
        return userRepository.findByEmailIgnoreCase(email)
                .map(user -> ResponseEntity.ok(Map.of("role", user.getRole())))
                .or(() -> adminRepository.findByEmailIgnoreCase(email)
                        .map(admin -> ResponseEntity.ok(Map.of("role", admin.getRole())))
                )
                .orElseGet(() -> ResponseEntity.status(404).body(Map.of("error", "User not found")));
    }

    @PostMapping("/login")
    public ResponseEntity<?> login(@RequestBody LoginDto loginDto) {
        return handleLogin(loginDto, false);
    }

    @PostMapping("/admin/login")
    public ResponseEntity<?> adminLogin(@RequestBody LoginDto loginDto) {
        return handleLogin(loginDto, true);
    }

    private ResponseEntity<?> handleLogin(LoginDto loginDto, boolean isAdmin) {
        try {
            String token = authService.login(loginDto);

            String email = loginDto.getEmail();
            String role = isAdmin ? "ROLE_ADMIN" : "ROLE_USER";

            Map<String, Object> response = new HashMap<>();
            response.put("accessToken", token);
            response.put("role", role);

            if (isAdmin) {
                Admin admin = adminRepository.findByEmailIgnoreCase(email)
                        .orElseThrow(() -> new RuntimeException("Admin not found"));
                response.put("email", admin.getEmail());
                response.put("name", admin.getName());
            } else {
                User user = userRepository.findByEmailIgnoreCase(email)
                        .orElseThrow(() -> new RuntimeException("User not found"));
                response.put("email", user.getEmail());
                response.put("name", user.getName());
            }

            return ResponseEntity.ok(response);
        } catch (RuntimeException ex) {
            return ResponseEntity.badRequest().body(Map.of("error", ex.getMessage()));
        }
    }
}
